//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingFirstOrderArticleIdOnSubscription.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string SessionId { get; set; }
        public short ItemId { get; set; }
        public short SubItemId { get; set; }
        public Nullable<short> Related_ItemId { get; set; }
        public Nullable<short> Related_SubItemId { get; set; }
        public Nullable<byte> GoodsType { get; set; }
        public string CategoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<short> UnitId { get; set; }
        public Nullable<byte> CompType { get; set; }
        public string CompJobFile { get; set; }
        public Nullable<byte> IsDoneImageComp { get; set; }
        public string CompErr { get; set; }
        public string CategoryName { get; set; }
        public string ProductName { get; set; }
        public string CartAddText1 { get; set; }
        public string CartAddText2 { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> Qty { get; set; }
        public string UnitText { get; set; }
        public Nullable<decimal> SubTotalPrice { get; set; }
        public Nullable<decimal> orgSubTotalPrice { get; set; }
        public Nullable<short> PreviewImg { get; set; }
        public Nullable<short> OptionId { get; set; }
        public string TemplateId { get; set; }
        public Nullable<decimal> WorkPrice { get; set; }
        public string QtyEditUrl { get; set; }
        public string Details { get; set; }
        public string DataDetails { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public Nullable<bool> ImageCompletion { get; set; }
        public string RestoreUrl { get; set; }
        public string RestorePassword { get; set; }
        public Nullable<System.DateTime> RestoreExpireDate { get; set; }
        public Nullable<short> sendImageType { get; set; }
        public Nullable<short> I2Flg { get; set; }
    }
}
