//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingFirstOrderArticleIdOnSubscription.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class crtEntities : DbContext
    {
        public crtEntities()
            : base("name=crtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<OrderManage> OrderManage { get; set; }
        public virtual DbSet<t_subscription> t_subscription { get; set; }
        public virtual DbSet<UserManage> UserManage { get; set; }
    
        public virtual int CloseSymmetricKey()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseSymmetricKey");
        }
    
        public virtual int OpenSymmetricKey()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OpenSymmetricKey");
        }
    }
}
