//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingFirstOrderArticleIdOnSubscription.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManage
    {
        public string SessionId { get; set; }
        public string TEMP_ORDER_ID { get; set; }
        public Nullable<byte> UserRank { get; set; }
        public Nullable<int> customer { get; set; }
        public string AspJointID { get; set; }
        public string ASP_ID { get; set; }
        public string AspSession { get; set; }
        public string AspUserID { get; set; }
        public Nullable<System.DateTime> PlacedOrder { get; set; }
        public string HiResImgPath { get; set; }
        public Nullable<System.DateTime> HiResDelSchedule { get; set; }
        public Nullable<bool> IsClearHiRes { get; set; }
        public string WorkImgUrl { get; set; }
        public Nullable<System.DateTime> WorkDelSchedule { get; set; }
        public Nullable<bool> IsClearWork { get; set; }
        public Nullable<System.DateTime> AccessDateTime { get; set; }
        public string LandingPage { get; set; }
        public string QuerryString { get; set; }
        public string UserIpAddress { get; set; }
        public string UserHostname { get; set; }
        public string Refer { get; set; }
        public string UserAgent { get; set; }
        public string UserLanguage { get; set; }
        public string ASPSubID { get; set; }
        public string CouponId { get; set; }
    }
}
