//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingFirstOrderArticleIdOnSubscription.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManage
    {
        public string SessionId { get; set; }
        public string SiteSession { get; set; }
        public string TEMP_ORDER_ID { get; set; }
        public string TEMP_ORDER_DETAIL_ID { get; set; }
        public Nullable<short> ORDER_ACTION { get; set; }
        public string ORDER_ID { get; set; }
        public string EC_ORDER_DATE { get; set; }
        public Nullable<short> ShipType { get; set; }
        public Nullable<short> PayType { get; set; }
        public string ShipDeliveryNo { get; set; }
        public Nullable<System.DateTime> ShipmentDay { get; set; }
        public string PRINT_SUBTOTAL { get; set; }
        public string DELIVERY_SUBSTITUTE_FEE { get; set; }
        public string ShipFee { get; set; }
        public string PaymentFee { get; set; }
        public string PRINT_TOTAL { get; set; }
        public string CAMPAIGN_NAME { get; set; }
        public string DISCOUNT_RATE { get; set; }
        public string CAMPAIGN_CODE { get; set; }
        public byte[] LASTNAME { get; set; }
        public byte[] FIRSTNAME { get; set; }
        public byte[] LASTNAME_KANA { get; set; }
        public byte[] FIRSTNAME_KANA { get; set; }
        public byte[] POST1 { get; set; }
        public byte[] POST2 { get; set; }
        public byte[] ADDRESS1 { get; set; }
        public byte[] ADDRESS2 { get; set; }
        public byte[] ADDRESS3 { get; set; }
        public byte[] ADDRESS4 { get; set; }
        public byte[] ADDRESS5 { get; set; }
        public byte[] TEL1 { get; set; }
        public byte[] TEL2 { get; set; }
        public byte[] TEL3 { get; set; }
        public byte[] ORDER_EMAIL { get; set; }
        public byte[] CompanyName { get; set; }
        public byte[] Division { get; set; }
        public byte[] Title { get; set; }
        public byte[] DELIVERY_LASTNAME { get; set; }
        public byte[] DELIVERY_FIRSTNAME { get; set; }
        public byte[] DELIVERY_LASTNAME_KANA { get; set; }
        public byte[] DELIVERY_FIRSTNAME_KANA { get; set; }
        public byte[] DELIVERY_POST1 { get; set; }
        public byte[] DELIVERY_POST2 { get; set; }
        public byte[] DELIVERY_ADDRESS1 { get; set; }
        public byte[] DELIVERY_ADDRESS2 { get; set; }
        public byte[] DELIVERY_ADDRESS3 { get; set; }
        public byte[] DELIVERY_ADDRESS4 { get; set; }
        public byte[] DELIVERY_ADDRESS5 { get; set; }
        public byte[] DELIVERY_TEL1 { get; set; }
        public byte[] DELIVERY_TEL2 { get; set; }
        public byte[] DELIVERY_TEL3 { get; set; }
        public byte[] DELIVERY_CompanyName { get; set; }
        public byte[] DELIVERY_Division { get; set; }
        public byte[] DELIVERY_Title { get; set; }
        public string CouponId { get; set; }
        public Nullable<System.DateTime> Sold_Date { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public Nullable<System.DateTime> LabSend_Date { get; set; }
        public string Remarks { get; set; }
        public short WebDeliType { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public string HistoryId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> date_EC_DATE { get; set; }
        public string PRINT_SUBTOTAL_ORG { get; set; }
        public Nullable<bool> CouponCanceled { get; set; }
        public string ORDER_EMAIL_HASH { get; set; }
    }
}
