//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingFirstOrderArticleIdOnSubscription.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_subscription
    {
        public int customer_number { get; set; }
        public string recurring_id { get; set; }
        public int status { get; set; }
        public bool ordered { get; set; }
        public int facter { get; set; }
        public System.DateTime start_at { get; set; }
        public System.DateTime end_at { get; set; }
        public int duration_months { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public bool has_error { get; set; }
        public bool needs_gmo_cancel { get; set; }
        public Nullable<int> change_amount { get; set; }
        public Nullable<bool> needs_update_creditcard { get; set; }
        public Nullable<System.DateTime> updated_at_recurring_credit { get; set; }
        public int article_id { get; set; }
    }
}
